# Generated by Django 3.2.7 on 2022-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
