# Generated by Django 3.2.7 on 2022-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_iso_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default=1, max_length=4, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
